title: Calice
description: Il social del vino italiano
url: https://barcolana.github.io
baseurl: /Calice

collections:
  vini:
    output: true
    permalink: /vini/:name/
  posts:
    output: true
    permalink: /blog/:name/

defaults:
  - scope:
      path: ""
      type: "vini"
    values:
      layout: vino
  - scope:
      path: ""
      type: "posts"
    values:
      layout: articolo