title: Calice
description: Il social del vino italiano
url: https://calice-vino.netlify.app

collections:
  vini:
    output: true
    permalink: /vini/:name/

defaults:
  - scope:
      path: ""
      type: "vini"
    values:
      layout: vino
