title: Calice
description: Il social del vino italiano
url: https://barcolana.github.io
baseurl: /Calice

collections:
  vini:
    output: true
    permalink: /Calice/vini/:name/

defaults:
  - scope:
      path: ""
      type: "vini"
    values:
      layout: vino
